baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "book"

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

[languages.ru]
  languageName = 'Russian'
  contentDir = 'content.ru'
  weight = 2

[menu]
[[menu.after]]
  name = "Github"
  url = "https://github.com/alex-shpak/hugo-book"
  weight = 10

[[menu.after]]
  name = "Hugo Themes"
  url = "https://themes.gohugo.io/hugo-book/"
  weight = 20

[params]
  BookMenuBundle = "/menu"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
